# Generated by Django 4.0.5 on 2022-06-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=200, verbose_name='Название самосвала')),
            ],
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=200, null=True, verbose_name='Модель самосвала')),
                ('capacity', models.IntegerField(default=0, null=True, verbose_name='Максимальная грузоподъемность')),
            ],
        ),
        migrations.CreateModel(
            name='TruckTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='Текущий вес')),
                ('model_name', models.ForeignKey(db_column='Модель', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tripweight.truckmodel')),
                ('truck_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tripweight.truck')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='model_name',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tripweight.truckmodel'),
        ),
    ]
