# Generated by Django 4.0.5 on 2022-06-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripweight', '0002_alter_truck_truck_name_alter_truckmodel_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucktrip',
            old_name='truck_name',
            new_name='truck',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_name',
        ),
        migrations.RemoveField(
            model_name='truckmodel',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='trucktrip',
            name='model_name',
        ),
        migrations.AddField(
            model_name='truck',
            name='model',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tripweight.truckmodel'),
        ),
        migrations.AddField(
            model_name='truck',
            name='name',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название самосвала'),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='name',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Модель самосвала'),
        ),
        migrations.AddField(
            model_name='trucktrip',
            name='truck_model',
            field=models.ForeignKey(db_column='Модель', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tripweight.truckmodel'),
        ),
    ]
